### PR TITLE
go-licenses 1.1.1, add maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- have removed the unknown files patch for now
- blocks https://github.com/conda-forge/staged-recipes/pull/18692
  - the 1.x line offers the `--ignore` flag, which is often useful for the package-under-build... in this case, `minio-client` is AGPL-3.0 licensed, so we need to ignore that specific member of the "forbidden" list
- adds self as maintainer :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/go-licenses ready for review

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/go-licenses ready for review (still, but as of a week ago)

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by dhirschfeld** [comment]
Hi @bollwyvl 👋 
I'm on holiday (for a month) and mostly unplugged so have a huge list of notifications to catch up on when I'm back. In any case, just wanted to say sorry for being unresponsive and thanks for picking up the slack here! :heart:

**Comment by bollwyvl** [comment]
No worries, enjoy!

**Pull request merged**
