### PR TITLE
Update to commit 44

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
`0001-Use-filepath.IsAbs.patch` failed to apply

**Comment by dhirschfeld** [comment]
```
+ mkdir -p /home/conda/feedstock_root/build_artifacts/go-licenses_1634908562698/_h_env_placehold/share/go-licenses
++ go env GOPATH
+ cp
    '/home/conda/feedstock_root/build_artifacts/go-licenses_1634908562698/work/gopath/pkg/mod/github.com/google/licenseclassifier@*-3043a050f148a588e7e0c84dce27579dfe17fd2d/licenses/licenses.db'
     /home/conda/feedstock_root/build_artifacts/go-licenses_1634908562698/_h_env_placehold/share/go-licenses/
cp: cannot stat
    `/home/conda/feedstock_root/build_artifacts/go-licenses_1634908562698/work/gopath/pkg/mod/github.com/google/licenseclassifier@*-3043a050f148a588e7e0c84dce27579dfe17fd2d/licenses/licenses.db':
    No such file or directory
```

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
Hi Dave,
thanks for getting back to the Go feedstocks! :100: 
I've been quite all over the place and didn't manage to maintain any of those. I recently saw that you've been added as a maintainer to a containers feedstock (or multiple? I have an ocean of unread notifications but didn't yet find the time of tranquility to sort through them -- sorry you got caught in my backlog there). I would definitely *like* to maintain those, but those always take a little more time and effort, because
- `containers-common` is an oddball since no "one true upstream" exists (https://github.com/containers/common is rather just the library than the shared config files that `conda-forge::containers-common` is) and the versioning from, e.g., Fedora's package changed from following https://github.com/containers/skopeo to https://github.com/containers/common to now (IIRC) some custom scheme that is now at epoch 4. I've not dug into what we should use regarding versioning but also regarding updated configs for `conda-forge::containers-common` now.
- They (esp the OCI runtimes, Podman, and the like) need some extra testing, because the build containers don't pass on through needed capabilities/devices to run container-in-container.
- The build scripts changed from time to time (wrt to following conventions like `DESTDIR`, usage of Go modules, etc.).
- The patches we have to make the binaries relocatable etc. have to be maintained.
  (But the patches to make thing compile under CentOS 6, we could ditch by now, TBH.)
- I'm not really up-to-date with the Go world; I *think* go modules are now on by default; I *think* `go install` should be used instead of `go get`; but I don't *know* much :laughing:.

(^-- It totally doesn't make sense to write these containers feedstock-specific things here, but hey, I just found the time to write now and we don't have a central place for these things to talk about -- maybe I should create a conda-forge group/team for that :thinking:.)

**Comment by dhirschfeld** [comment]
Hey @mbargull,
Thanks for the help here! :heart:  

My goal is just to get the containers feedstocks up to date but I've been running into all the issues you mentioned above! 😬 

I also don't know anything about `go` so I'm just bumbling about, nevertheless, I did manage to get `skopeo` to build: https://github.com/conda-forge/skopeo-feedstock/pull/17

It required some `DESTDIR` changes as well as pinning `go<1.16` to avoid:
```
F1014 01:51:09.774547    4507 main.go:43] errors for ["github.com/containers/skopeo/cmd/skopeo"]:
github.com/containers/skopeo/cmd/skopeo: -: no required module provides package github.com/containers/skopeo/cmd/skopeo: go.mod file not found in current directory or any parent directory; see 'go help modules'
```
> *I think go modules are now on by default*

I think that's true from 1.16 onwards hence I tried the pinning above which seemed to ~~fix~~avoid the problem.
https://go.dev/blog/go116-module-changes

----

I also managed to get [`buildah`](https://github.com/conda-forge/buildah-feedstock/pull/9) updated by just regenerating the patch. Hopefully, that was all that was required. I figured if there were latent bugs in there I'd flush them out by using it in practice!

----

Unfortunately, I haven't yet had any luck with podman :(
* https://github.com/conda-forge/podman-feedstock/pull/12

After regenerating the patch there I ran into an issue gathering the licenses so i ended up here, hoping updating this feedstock might just resolve that problem. Now that you've fixed this feedstock I'll give that a go!

> *But the patches to make thing compile under CentOS 6, we could ditch by now, TBH.*

That's the route I took with `podman` - [`a429361` (#12)](https://github.com/conda-forge/podman-feedstock/pull/12/commits/a429361aab0743e2b7a8927ee55bc17ce383a82d)

----

> *I recently saw that you've been added as a maintainer to a containers feedstock (or multiple?)*

Yeah, I added myself as a maintainer so I could help out (insofar as I'm able!) If it's just merging PRs or even updating a patch or two I can help out with that sort of grunt-work so you don't have to do it all by yourself.

----

> *`containers-common` is an oddball*

Yeah, I've only taken a quick look and wasn't quite sure what was going on and what the best way forward was. I was planning on trying to just update all the versions and see how far I got. I wasn't too hopeful that would work though :/

**Pull request merged**
